export let fruitEmojiObject = [
    {
        id: 1,
        emoji: 'https://www.emoji.family/api/emojis/🍎/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 2,
        emoji: 'https://www.emoji.family/api/emojis/🍊/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 3,
        emoji: 'https://www.emoji.family/api/emojis/🍋/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 4,
        emoji: 'https://www.emoji.family/api/emojis/🍌/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 5,
        emoji: 'https://www.emoji.family/api/emojis/🍉/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 6,
        emoji: 'https://www.emoji.family/api/emojis/🍇/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 7,
        emoji: 'https://www.emoji.family/api/emojis/🍓/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 8,
        emoji: 'https://www.emoji.family/api/emojis/🍒/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 9,
        emoji: 'https://www.emoji.family/api/emojis/🍑/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 10,
        emoji: 'https://www.emoji.family/api/emojis/🍍/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 11,
        emoji: 'https://www.emoji.family/api/emojis/🥥/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 12,
        emoji: 'https://www.emoji.family/api/emojis/🥝/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 13,
        emoji: 'https://www.emoji.family/api/emojis/🍆/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 14,
        emoji: 'https://www.emoji.family/api/emojis/🥑/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 15,
        emoji: 'https://www.emoji.family/api/emojis/🥦/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 16,
        emoji: 'https://www.emoji.family/api/emojis/🥬/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 17,
        emoji: 'https://www.emoji.family/api/emojis/🌽/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 18,
        emoji: 'https://www.emoji.family/api/emojis/🥕/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 19,
        emoji: 'https://www.emoji.family/api/emojis/🍎/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 20,
        emoji: 'https://www.emoji.family/api/emojis/🍊/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 21,
        emoji: 'https://www.emoji.family/api/emojis/🍋/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 22,
        emoji: 'https://www.emoji.family/api/emojis/🍌/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 23,
        emoji: 'https://www.emoji.family/api/emojis/🍉/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 24,
        emoji: 'https://www.emoji.family/api/emojis/🍇/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 25,
        emoji: 'https://www.emoji.family/api/emojis/🍓/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 26,
        emoji: 'https://www.emoji.family/api/emojis/🍒/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 27,
        emoji: 'https://www.emoji.family/api/emojis/🍑/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 28,
        emoji: 'https://www.emoji.family/api/emojis/🍍/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 29,
        emoji: 'https://www.emoji.family/api/emojis/🥥/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 30,
        emoji: 'https://www.emoji.family/api/emojis/🥝/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 31,
        emoji: 'https://www.emoji.family/api/emojis/🍆/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 32,
        emoji: 'https://www.emoji.family/api/emojis/🥑/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 33,
        emoji: 'https://www.emoji.family/api/emojis/🥦/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 34,
        emoji: 'https://www.emoji.family/api/emojis/🥬/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 35,
        emoji: 'https://www.emoji.family/api/emojis/🌽/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 36,
        emoji: 'https://www.emoji.family/api/emojis/🥕/fluentflat/svg',
        hidden: true,
        matched: false,
    },
]









export let animalEmojiObject = [
    {
        id: 1,
        emoji: 'https://www.emoji.family/api/emojis/🍕/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 2,
        emoji: 'https://www.emoji.family/api/emojis/🍔/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 3,
        emoji: 'https://www.emoji.family/api/emojis/🍟/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 4,
        emoji: 'https://www.emoji.family/api/emojis/🌭/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 5,
        emoji: 'https://www.emoji.family/api/emojis/🥩/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 6,
        emoji: 'https://www.emoji.family/api/emojis/🍚/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 7,
        emoji: 'https://www.emoji.family/api/emojis/🍩/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 8,
        emoji: 'https://www.emoji.family/api/emojis/🧁/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 9,
        emoji: 'https://www.emoji.family/api/emojis/🍺/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 10,
        emoji: 'https://www.emoji.family/api/emojis/🍷/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 11,
        emoji: 'https://www.emoji.family/api/emojis/🍫/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 12,
        emoji: 'https://www.emoji.family/api/emojis/🍗/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 13,
        emoji: 'https://www.emoji.family/api/emojis/🌮/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 14,
        emoji: 'https://www.emoji.family/api/emojis/🥞/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 15,
        emoji: 'https://www.emoji.family/api/emojis/🥓/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 16,
        emoji: 'https://www.emoji.family/api/emojis/🍙/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 17,
        emoji: 'https://www.emoji.family/api/emojis/🎂/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 18,
        emoji: 'https://www.emoji.family/api/emojis/☕/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 19,
        emoji: 'https://www.emoji.family/api/emojis/🍕/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 20,
        emoji: 'https://www.emoji.family/api/emojis/🍔/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 21,
        emoji: 'https://www.emoji.family/api/emojis/🍟/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 22,
        emoji: 'https://www.emoji.family/api/emojis/🌭/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 23,
        emoji: 'https://www.emoji.family/api/emojis/🥩/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 24,
        emoji: 'https://www.emoji.family/api/emojis/🍚/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 25,
        emoji: 'https://www.emoji.family/api/emojis/🍩/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 26,
        emoji: 'https://www.emoji.family/api/emojis/🧁/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 27,
        emoji: 'https://www.emoji.family/api/emojis/🍺/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 28,
        emoji: 'https://www.emoji.family/api/emojis/🍷/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 29,
        emoji: 'https://www.emoji.family/api/emojis/🍫/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 30,
        emoji: 'https://www.emoji.family/api/emojis/🍗/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 31,
        emoji: 'https://www.emoji.family/api/emojis/🌮/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 32,
        emoji: 'https://www.emoji.family/api/emojis/🥞/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 33,
        emoji: 'https://www.emoji.family/api/emojis/🥓/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 34,
        emoji: 'https://www.emoji.family/api/emojis/🍙/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 35,
        emoji: 'https://www.emoji.family/api/emojis/🎂/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 36,
        emoji: 'https://www.emoji.family/api/emojis/☕/fluentflat/svg',
        hidden: true,
        matched: false,
    },
]

export function getRandomRevealTextOption(): string {
    let textOptions = ['Look carefully!','Take a good look!','Peekaboo 🙈']
    let index = Math.floor(Math.random() * 3);
    return textOptions[index]
  }



export let stuffEmojiObject = [
    {
        id: 1,
        emoji: 'https://www.emoji.family/api/emojis/👑/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 2,
        emoji: 'https://www.emoji.family/api/emojis/💎/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 3,
        emoji: 'https://www.emoji.family/api/emojis/⚽/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 4,
        emoji: 'https://www.emoji.family/api/emojis/🏀/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 5,
        emoji: 'https://www.emoji.family/api/emojis/✈️/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 6,
        emoji: 'https://www.emoji.family/api/emojis/🚀/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 7,
        emoji: 'https://www.emoji.family/api/emojis/🧻/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 8,
        emoji: 'https://www.emoji.family/api/emojis/🛎️/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 9,
        emoji: 'https://www.emoji.family/api/emojis/🗼/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 10,
        emoji: 'https://www.emoji.family/api/emojis/🚗/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 11,
        emoji: 'https://www.emoji.family/api/emojis/🍄/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 12,
        emoji: 'https://www.emoji.family/api/emojis/🍁/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 13,
        emoji: 'https://www.emoji.family/api/emojis/🌼/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 14,
        emoji: 'https://www.emoji.family/api/emojis/🧸/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 15,
        emoji: 'https://www.emoji.family/api/emojis/🎸/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 16,
        emoji: 'https://www.emoji.family/api/emojis/🗿/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 17,
        emoji: 'https://www.emoji.family/api/emojis/🎹/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 18,
        emoji: 'https://www.emoji.family/api/emojis/❤️/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 19,
        emoji: 'https://www.emoji.family/api/emojis/👑/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 20,
        emoji: 'https://www.emoji.family/api/emojis/💎/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 21,
        emoji: 'https://www.emoji.family/api/emojis/⚽/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 22,
        emoji: 'https://www.emoji.family/api/emojis/🏀/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 23,
        emoji: 'https://www.emoji.family/api/emojis/✈️/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 24,
        emoji: 'https://www.emoji.family/api/emojis/🚀/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 25,
        emoji: 'https://www.emoji.family/api/emojis/🧻/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 26,
        emoji: 'https://www.emoji.family/api/emojis/🛎️/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 27,
        emoji: 'https://www.emoji.family/api/emojis/🗼/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 28,
        emoji: 'https://www.emoji.family/api/emojis/🚗/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 29,
        emoji: 'https://www.emoji.family/api/emojis/🍄/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 30,
        emoji: 'https://www.emoji.family/api/emojis/🍁/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 31,
        emoji: 'https://www.emoji.family/api/emojis/🌼/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 32,
        emoji: 'https://www.emoji.family/api/emojis/🧸/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 33,
        emoji: 'https://www.emoji.family/api/emojis/🎸/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 34,
        emoji: 'https://www.emoji.family/api/emojis/🗿/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 35,
        emoji: 'https://www.emoji.family/api/emojis/🎹/fluentflat/svg',
        hidden: true,
        matched: false,
    },
    {
        id: 36,
        emoji: 'https://www.emoji.family/api/emojis/❤️/fluentflat/svg',
        hidden: true,
        matched: false,
    },
]