export let fruitEmojiObject = [
    {
        id: 1,
        emoji: '🍎',
        hidden: true,
        matched: false,
    },
    {
        id: 2,
        emoji: '🍊',
        hidden: true,
        matched: false,
    },
    {
        id: 3,
        emoji: '🍋',
        hidden: true,
        matched: false,
    },
    {
        id: 4,
        emoji: '🍌',
        hidden: true,
        matched: false,
    },
    {
        id: 5,
        emoji: '🍉',
        hidden: true,
        matched: false,
    },
    {
        id: 6,
        emoji: '🍇',
        hidden: true,
        matched: false,
    },
    {
        id: 7,
        emoji: '🍓',
        hidden: true,
        matched: false,
    },
    {
        id: 8,
        emoji: '🍒',
        hidden: true,
        matched: false,
    },
    {
        id: 9,
        emoji: '🍑',
        hidden: true,
        matched: false,
    },
    {
        id: 10,
        emoji: '🍍',
        hidden: true,
        matched: false,
    },
    {
        id: 11,
        emoji: '🥥',
        hidden: true,
        matched: false,
    },
    {
        id: 12,
        emoji: '🥝',
        hidden: true,
        matched: false,
    },
    {
        id: 13,
        emoji: '🍆',
        hidden: true,
        matched: false,
    },
    {
        id: 14,
        emoji: '🥑',
        hidden: true,
        matched: false,
    },
    {
        id: 15,
        emoji: '🥦',
        hidden: true,
        matched: false,
    },
    {
        id: 16,
        emoji: '🥬',
        hidden: true,
        matched: false,
    },
    {
        id: 17,
        emoji: '🌽',
        hidden: true,
        matched: false,
    },
    {
        id: 18,
        emoji: '🥕',
        hidden: true,
        matched: false,
    },
    {
        id: 19,
        emoji: '🍎',
        hidden: true,
        matched: false,
    },
    {
        id: 20,
        emoji: '🍊',
        hidden: true,
        matched: false,
    },
    {
        id: 21,
        emoji: '🍋',
        hidden: true,
        matched: false,
    },
    {
        id: 22,
        emoji: '🍌',
        hidden: true,
        matched: false,
    },
    {
        id: 23,
        emoji: '🍉',
        hidden: true,
        matched: false,
    },
    {
        id: 24,
        emoji: '🍇',
        hidden: true,
        matched: false,
    },
    {
        id: 25,
        emoji: '🍓',
        hidden: true,
        matched: false,
    },
    {
        id: 26,
        emoji: '🍒',
        hidden: true,
        matched: false,
    },
    {
        id: 27,
        emoji: '🍑',
        hidden: true,
        matched: false,
    },
    {
        id: 28,
        emoji: '🍍',
        hidden: true,
        matched: false,
    },
    {
        id: 29,
        emoji: '🥥',
        hidden: true,
        matched: false,
    },
    {
        id: 30,
        emoji: '🥝',
        hidden: true,
        matched: false,
    },
    {
        id: 31,
        emoji: '🍆',
        hidden: true,
        matched: false,
    },
    {
        id: 32,
        emoji: '🥑',
        hidden: true,
        matched: false,
    },
    {
        id: 33,
        emoji: '🥦',
        hidden: true,
        matched: false,
    },
    {
        id: 34,
        emoji: '🥬',
        hidden: true,
        matched: false,
    },
    {
        id: 35,
        emoji: '🌽',
        hidden: true,
        matched: false,
    },
    {
        id: 36,
        emoji: '🥕',
        hidden: true,
        matched: false,
    },
]